export const AuditAction = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_LOGOUT: "USER_LOGOUT",
  TOKEN_REFRESHED: "TOKEN_REFRESHED",

  DOCTOR_CREATED: "DOCTOR_CREATED",
  DOCTOR_VERIFIED: "DOCTOR_VERIFIED",

  AVAILABILITY_CREATED: "AVAILABILITY_CREATED",
  AVAILABILITY_UPDATED: "AVAILABILITY_UPDATED",
  AVAILABILITY_DELETED: "AVAILABILITY_DELETED",

  CONSULTATION_BOOKED: "CONSULTATION_BOOKED",
  CONSULTATION_STARTED: "CONSULTATION_STARTED",
  CONSULTATION_COMPLETED: "CONSULTATION_COMPLETED",
  CONSULTATION_CANCELLED: "CONSULTATION_CANCELLED",
  CONSULTATION_NO_SHOW: "CONSULTATION_NO_SHOW",

  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_VERIFICATION_SUCCESS: "PAYMENT_VERIFICATION_SUCCESS",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUND_CREATED: "PAYMENT_REFUND_CREATED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",

  PRESCRIPTION_CREATED: "PRESCRIPTION_CREATED",

  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",

  ADMIN_ACTION: "ADMIN_ACTION",
} as const;

export type AuditAction =
  (typeof AuditAction)[keyof typeof AuditAction];